<a href="https://colab.research.google.com/github/HectorElizarraraz/CPSC456Assignment3/blob/main/Project6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##This project was completed by:
##Hector Elizarraraz, CWID: 890228935
##Marco Salinas, CWID: 890589393
##CPSC 483-02

### 1.Dowmload bank-additional.zip and extract its contents. Since the dataset is large and some algorithims we will use can be time consuming, we will train with bank-additional.csv, which is a subset of the original dataset.
###Once our models are trained, we will test against the full dataset, which is in bank-additional-full.csv. ###

###The archive also contains a text file, bank-additional-names.txt, which describes the dataset and what each column represents.###


###2. Use read_csv() to load and examine the training and test sets. Unlike most CSV files, the separator is actually ';' rather than ','. ###

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

cols = ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month',
        'day_of_week', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'eurinor3m', 'nr.employed', 'y']
print('Training set:')
train = pd.read_csv("/content/bank-additional.csv", header=None, names=cols, sep=';')
train




Training set:


age          job  marital  ...  eurinor3m  nr.employed   y
0     age          job  marital  ...  euribor3m  nr.employed   y
1      30  blue-collar  married  ...      1.313       5099.1  no
2      39     services   single  ...      4.855         5191  no
3      25     services  married  ...      4.962       5228.1  no
4      38     services  married  ...      4.959       5228.1  no
...   ...          ...      ...  ...        ...          ...  ..
4115   30       admin.  married  ...      4.958       5228.1  no
4116   39       admin.  married  ...      4.959       5228.1  no
4117   27      student   single  ...      1.354       5099.1  no
4118   58       admin.  married  ...      4.966       5228.1  no
4119   34   management   single  ...       4.12       5195.8  no

[4120 rows x 21 columns]

In [ ]:
print('Test Set:')
test = pd.read_csv("/content/bank-additional-full.csv", header=None, names=cols, sep=';')
test

Test Set:


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,10,11,12,13,15,16,17,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


age          job  marital  ...  eurinor3m  nr.employed    y
0      age          job  marital  ...  euribor3m  nr.employed    y
1       56    housemaid  married  ...      4.857         5191   no
2       57     services  married  ...      4.857         5191   no
3       37     services  married  ...      4.857         5191   no
4       40       admin.  married  ...      4.857         5191   no
...    ...          ...      ...  ...        ...          ...  ...
41184   73      retired  married  ...      1.028       4963.6  yes
41185   46  blue-collar  married  ...      1.028       4963.6   no
41186   56      retired  married  ...      1.028       4963.6   no
41187   44   technician  married  ...      1.028       4963.6  yes
41188   74      retired  married  ...      1.028       4963.6   no

[41189 rows x 21 columns]

###3. The training and test DataFrames will need some significant preprocessing before they can be used:###

### Several of the features are categorical variables and will need to be turned into numbers before they can be used by ML algorithms. The simplest way to accomplish this is to use dummy coding using get_dummies().###

###Some algorithms (e.g. logistic regression) have problems with collinear features. If you use one-hot encoding, one dummy variable will be a linear combination of the other dummy variables, so be sure to pass drop_first=True.####

  


In [ ]:
# data preprocessing
# non-numerical features: job, marital, education, default, loan, contact, month, day_of_week, poutcome
# use get_dummies to give numerical values to categorical features
trainFormatted = pd.get_dummies(train, columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome'], drop_first=True)
# remove target variable and duration feature
trainTarget = trainFormatted['y']
trainFormatted = trainFormatted.drop(['duration', 'y'], axis=1)

# Need to standardize numerical values for KNN and SVM

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

trainFormatted  = trainFormatted.drop(trainFormatted.index[0])
trainTarget  = trainTarget.drop(trainTarget.index[0])

trainFormatted = scaler.fit_transform(trainFormatted)
trainFormatted



array([[-0.98075178, -0.20922829,  0.20103134, ...,  0.41130767,
         0.        , -0.18895848],
       [-0.10799146,  0.56963417,  0.20103134, ...,  0.41130767,
         0.        , -0.18895848],
       [-1.46561862, -0.59865952,  0.20103134, ...,  0.41130767,
         0.        , -0.18895848],
       ...,
       [-1.27167189, -0.20922829,  0.20103134, ..., -2.43127   ,
         0.        , -0.18895848],
       [ 1.73450254, -0.59865952,  0.20103134, ...,  0.41130767,
         0.        , -0.18895848],
       [-0.59285831, -0.59865952,  0.20103134, ...,  0.41130767,
         0.        , -0.18895848]])

In [ ]:
testFormatted = pd.get_dummies(test, columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome'], drop_first=True)
# remove target variable and duration feature
testTarget= testFormatted['y']
testFormatted = testFormatted.drop(['duration', 'y'], axis=1)

# Need to standardize numerical values for KNN and SVM

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

testFormatted = testFormatted.drop(testFormatted.index[0])
testTarget = testTarget.drop(testTarget.index[0])

testFormatted = scaler.fit_transform(testFormatted)
testFormatted

array([[ 1.53303429, -0.56592197,  0.1954139 , ...,  0.39770593,
         0.        , -0.1857    ],
       [ 1.62899323, -0.56592197,  0.1954139 , ...,  0.39770593,
         0.        , -0.1857    ],
       [-0.29018564, -0.56592197,  0.1954139 , ...,  0.39770593,
         0.        , -0.1857    ],
       ...,
       [ 1.53303429, -0.20490853,  0.1954139 , ...,  0.39770593,
         0.        , -0.1857    ],
       [ 0.38152696, -0.56592197,  0.1954139 , ...,  0.39770593,
         0.        , -0.1857    ],
       [ 3.26029527,  0.15610492,  0.1954139 , ..., -2.51442063,
         0.        , -0.1857    ]])

###Per bank-additional-names.txt, the feature duration “should be discarded if the intention is to have a realistic predictive model,” so removed. ###


###The feature y (or y_yes after dummy coding) is the target, so should be removed.###

###Some algorithms (e.g. KNN and SVM) require non-categorical features to be standardized. ###

###4. Fit Naive Bayes, KNN, and SVM classifiers to the training set, then score each classifier on the test set. Which classifier has the highest accuracy? ###

In [ ]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
X = trainFormatted
y = trainTarget
gnb = GaussianNB()

gnb.fit(X, y)
print("Naive Bayes Score:")
print(gnb.score(testFormatted, testTarget))

# KNN 
from sklearn.neighbors import KNeighborsClassifier
kneighs = KNeighborsClassifier(n_neighbors = 64)

kneighs.fit(X,y)
print("KNN Score: ")
print(kneighs.score(testFormatted, testTarget))

# SVM 
from sklearn.svm import SVC
svc = SVC()

svc.fit(X,y)

print("SVM Score: " )
print(svc.score(testFormatted, testTarget))


Naive Bayes Score:
0.8873458288821987
KNN Score: 
0.8980771098378169
SVM Score: 
0.898222783334952


The SVM classifier has the highest accuracy.

###5. These numbers look pretty good, but let’s take another look at the data. How many values in the training set have y_yes = 0, and how many have y_yes = 1? What would be the accuracy if we simply assumed that no customer ever subscribed to the product? ###

In [ ]:
noCount = 0
yesCount = 0
for x in trainTarget:
  if x == 'no':
    noCount +=1
  else:
    yesCount += 1

print("NOs")
print(noCount)

print("Yes")
print(yesCount)

NOs
3668
Yes
451


###6. Use np.zeros_like() to create a target vector representing the output of the “dumb” classifier of experiment (5), then create a confusion matrix and find its AUC. ###

In [ ]:
# create a target vector
zeroTarget = []
for x in trainTarget:
  zeroTarget.append(0)
# create confusion matrix
myArray = [ ]
for x in trainTarget:
  if x == 'no':
    myArray.append(0)
  else:
    myArray.append(1)
from sklearn.metrics import confusion_matrix
pred = kneighs.predict(trainFormatted)
print("This is the confusion matrix: ")
print(confusion_matrix(zeroTarget, myArray))

# now lets find teh AUC score
arr = []
for x in pred:
  if x == 'no':
    arr.append(0)
  else:
    arr.append(1)
from sklearn.metrics import roc_auc_score
print("THis is our area under the curve score: ")
print(roc_auc_score(myArray, arr))

This is the confusion matrix: 
[[3668  451]
 [   0    0]]
THis is our area under the curve score: 
0.5858654704074552


###7. Create a confusion matrix and find the AUC for each of the classifiers of experiment (4). Is the best classifier the one with the highest accuracy? ###


In [ ]:
#confusion matrix and AUC score for Naive bayes classifier
gnb_pred = gnb.predict(trainFormatted)
print("This is oiur confusion matrix for Naives Bayes: ")
print(confusion_matrix(y,gnb_pred ))

print("This is our AUC score: ")

num_y = []
for x in y:
  if x == 'no':
    num_y.append(0)
  else:
    num_y.append(1)

num_gnb_pred = []
for x in gnb_pred:
  if x == 'no':
    num_gnb_pred.append(0)
  else:
    num_gnb_pred.append(1)


print(roc_auc_score(num_y, num_gnb_pred))


# comfusion matric and AUC score for KNN
kneighs_pred = kneighs.predict(trainFormatted)
print("This is the confusion matrix: ")
print(confusion_matrix(y, kneighs_pred))

print("THis is our AUC score for KNN")
num_kneighs_pred = []
for x in kneighs_pred:
  if x =='no':
    num_kneighs_pred.append(0)
  else:
    num_kneighs_pred.append(1)
print(roc_auc_score(num_y, num_kneighs_pred))

# confusion matrix and AUC score for SVM

svc_pred = svc.predict(trainFormatted)

print("THis is our confusion matrix for SVM: ")
print(confusion_matrix(y, svc_pred))

print("This is our AUC score for SVM: ")
num_svc_pred = []
for x in svc_pred:
  if x == 'no':
    num_svc_pred.append(0)
  else:
    num_svc_pred.append(1)
print(roc_auc_score(num_y, num_svc_pred))

This is oiur confusion matrix for Naives Bayes: 
[[ 508 3160]
 [  17  434]]
This is our AUC score: 
0.5504005396948982
This is the confusion matrix: 
[[3631   37]
 [ 369   82]]
THis is our AUC score for KNN
0.5858654704074552
THis is our confusion matrix for SVM: 
[[3655   13]
 [ 322  129]]
This is our AUC score for SVM: 
0.6412434381853486


##There is a correlation between accuracy and the best classifier as the accuracy increases our classifier is also a bettter prediction. However it still produces sub-standard results. ##

###8. One of the easiest ways to deal with an unbalanced dataset is random oversampling. This can be done with an imblearn.over_sampling.RandomOverSampler object. Use fit_resample() to generate a balanced training set.###

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state =42 )

X_resampled, y_resampled= ros.fit_resample(trainFormatted, trainTarget)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


###9. Repeat experiments (4) and (7) on the balanced training set of experiment (8). Which classifier performs the best, and how much better is its performance? ###


In [ ]:
# Naive Bayes
gnb = GaussianNB()

gnb.fit(X_resampled, y_resampled)
print("Naive Bayes Score:")
print(gnb.score(testFormatted, testTarget))
# KNN
kneighs = KNeighborsClassifier(n_neighbors = 64)

kneighs.fit(X_resampled,y_resampled)
print("KNN Score: ")
print(kneighs.score(testFormatted, testTarget))
# SVM
svc = SVC()

svc.fit(X_resampled,y_resampled)

print("SVM Score: " )
print(svc.score(testFormatted, testTarget))

# lets see the yes and no's
noCount = 0
yesCount = 0
for x in X_resampled:
  if x == 'no':
    noCount +=1
  else:
    yesCount += 1

print("NOs")
print(noCount)

print("Yes")
print(yesCount)

# create a Confusion Matrix
#confusion matrix and AUC score for Naive bayes classifier
gnb_pred = gnb.predict(trainFormatted)
print("This is oiur confusion matrix for Naives Bayes: ")
print(confusion_matrix(y,gnb_pred ))

print("This is our AUC score: ")

num_y = []
for x in y:
  if x == 'no':
    num_y.append(0)
  else:
    num_y.append(1)

num_gnb_pred = []
for x in gnb_pred:
  if x == 'no':
    num_gnb_pred.append(0)
  else:
    num_gnb_pred.append(1)


print(roc_auc_score(num_y, num_gnb_pred))


# comfusion matric and AUC score for KNN
kneighs_pred = kneighs.predict(trainFormatted)
print("This is the confusion matrix: ")
print(confusion_matrix(y, kneighs_pred))

print("THis is our AUC score for KNN")
num_kneighs_pred = []
for x in kneighs_pred:
  if x =='no':
    num_kneighs_pred.append(0)
  else:
    num_kneighs_pred.append(1)
print(roc_auc_score(num_y, num_kneighs_pred))

# confusion matrix and AUC score for SVM

svc_pred = svc.predict(trainFormatted)

print("THis is our confusion matrix for SVM: ")
print(confusion_matrix(y, svc_pred))

print("This is our AUC score for SVM: ")
num_svc_pred = []
for x in svc_pred:
  if x == 'no':
    num_svc_pred.append(0)
  else:
    num_svc_pred.append(1)
print(roc_auc_score(num_y, num_svc_pred))

Naive Bayes Score:
0.8873458288821987
KNN Score: 
0.7877779935903662
SVM Score: 
0.8400019423132952
NOs
0
Yes
7336


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:25: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


This is oiur confusion matrix for Naives Bayes: 
[[ 390 3278]
 [  14  437]]
This is our AUC score: 
0.5376414220670411
This is the confusion matrix: 
[[2992  676]
 [ 153  298]]
THis is our AUC score for KNN
0.738228630427476
THis is our confusion matrix for SVM: 
[[3354  314]
 [  88  363]]
This is our AUC score for SVM: 
0.8596364071601458
